LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/AbcSize:
  Max: 25

# Rely on AbcSize
MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

require: rubocop-rspec

RSpec/NestedGroups:
  Enabled: false

# Too many implicit subjects
RSpec/NamedSubject:
  Enabled: false
